
services:
  mysql:
    image: mysql:8.0
    container_name: energix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: energix
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: energix-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=energix;user=root;password=Password123;TreatTinyAsBoolean=true"
      Jwt__Key: "gG5abeWPEn+UWLODPknAneZNv25ekCp48g2Gclxz7QI="
      Jwt__Issuer: "energix"
      Jwt__Audience: "energix-client"
      Jwt__ExpiresMinutes: "60"
    ports:
      - "5000:8080"
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
  dataprotection_keys:
