<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="src\BuildingBlocks\Energix.BuildingBlocks.csproj" />
      <Content Include="src\DeviceManagement\Infrastructure\Energix.DeviceManagement.Infrastructure.csproj" />
      <Content Include="src\Identity\Infrastructure\Energix.Identity.Infrastructure.csproj" />
      <Content Include="src\Notifications\Infrastructure\Energix.Notifications.Infrastructure.csproj" />
      <Content Include="src\Subscriptions\Infrastructure\Energix.Subscription.Infrastructure.csproj" />
    </ItemGroup>

</Project>
